
// Lookup tables for valid single-stick transformations
// Generated by analyzing 7-segment display patterns

const REMOVALS: Record<string, string[]> = {
    '0': [],
    '1': [],
    '2': [],
    '3': [],
    '4': [],
    '5': [],
    '6': ['5'],
    '7': ['1'],
    '8': ['0', '6', '9'],
    '9': ['3', '5'],
    '+': ['-'],
    '-': [],
    '=': []
};

const ADDITIONS: Record<string, string[]> = {
    '0': ['8'],
    '1': ['7'],
    '2': [],
    '3': ['9'],
    '4': [],
    '5': ['6', '9'],
    '6': ['8'],
    '7': [],
    '8': [],
    '9': ['8'],
    '+': [],
    '-': ['+'],
    '=': []
};

const SELF_MOVES: Record<string, string[]> = {
    '0': ['6', '9'],
    '1': [],
    '2': ['3'],
    '3': ['2', '5'],
    '4': [],
    '5': ['3'],
    '6': ['0', '9'],
    '7': [],
    '8': [],
    '9': ['0', '6'],
    '+': [],
    '-': [],
    '=': []
};

// Safe evaluation for simple equations with +, -
const safeEvaluate = (expr: string): number => {
    // Fast path for single number
    if (/^-?\d+$/.test(expr)) return parseInt(expr, 10);

    // Tokenize: split by operators but keep them
    // This regex splits by + or - and captures the delimiter
    const parts = expr.split(/([+-])/);

    let result = parseInt(parts[0], 10);
    if (isNaN(result)) return NaN;

    for (let i = 1; i < parts.length; i += 2) {
        const op = parts[i];
        const val = parseInt(parts[i+1], 10);

        if (isNaN(val)) return NaN;

        if (op === '+') result += val;
        else if (op === '-') result -= val;
    }

    return result;
};

export const solveEquation = (equation: string): string[] => {
    // Normalize: remove spaces
    const eq = equation.replace(/\s/g, '');
    const solutions = new Set<string>();
    const chars = eq.split('');

    // Optimization: Check for self-moves (1 stick moved within the same char)
    for (let i = 0; i < chars.length; i++) {
        const char = chars[i];
        const moves = SELF_MOVES[char];

        if (moves) {
            for (const newChar of moves) {
                const newChars = [...chars];
                newChars[i] = newChar;
                const newEq = newChars.join('');

                if (newEq !== eq) {
                    const [left, right] = newEq.split('=');
                    if (left && right) {
                        const leftVal = safeEvaluate(left);
                        const rightVal = safeEvaluate(right);
                        if (!isNaN(leftVal) && !isNaN(rightVal) && leftVal === rightVal) {
                            solutions.add(newEq);
                        }
                    }
                }
            }
        }
    }

    // Optimization: Check for moving a stick from one char to another
    for (let i = 0; i < chars.length; i++) {
        const sourceChar = chars[i];
        const sources = REMOVALS[sourceChar];

        if (sources && sources.length > 0) {
            // We can remove a stick from i
            for (const newSourceChar of sources) {
                // Now look for a place to put it
                for (let j = 0; j < chars.length; j++) {
                    if (i === j) continue;

                    const targetChar = chars[j];
                    const targets = ADDITIONS[targetChar];

                    if (targets && targets.length > 0) {
                        for (const newTargetChar of targets) {
                            const newChars = [...chars];
                            newChars[i] = newSourceChar;
                            newChars[j] = newTargetChar;
                            const newEq = newChars.join('');

                            if (newEq !== eq) {
                                const [left, right] = newEq.split('=');
                                if (left && right) {
                                    const leftVal = safeEvaluate(left);
                                    const rightVal = safeEvaluate(right);
                                    if (!isNaN(leftVal) && !isNaN(rightVal) && leftVal === rightVal) {
                                        solutions.add(newEq);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return Array.from(solutions);
};
